export const USER_LOGIN = 'APP_MERCHANT_LOGIN';
export const USER_LOGIN_SUCCESS = 'APP_MERCHANT_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'APP_MERCHANT_LOGIN_FAIL';

export const FETCH_ORDERS = 'APP_GET_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'APP_GET_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'APP_GET_ORDERS_FAIL';

export const UPDATE_ORDERS = 'APP_UPDATE_ORDERS';
export const UPDATE_ORDERS_SUCCESS = 'APP_UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_FAIL = 'APP_UPDATE_ORDERS_FAIL';